lib/banking_web/router.ex
defmodule BankingWeb.Router do
  use BankingWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :backoffice do
    plug BasicAuth, use_config: {:banking, :basic_auth}
  end

  scope "/", BankingWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/reports", BankingWeb do
    pipe_through [:browser, :backoffice]

    get "/", LogController, :index
  end

  scope "/api", BankingWeb do
    pipe_through :api

    resources "/users", UserController, only: [:create, :show], singleton: true
    get "/transactions/:id", TransactionController, :show
    post "/transactions/withdrawal", TransactionController, :withdrawal
    post "/transactions/deposit", TransactionController, :deposit
    post "/transactions/transfer", TransactionController, :transfer
  end
end

lib/banking/transactions/log.ex
defmodule Banking.Transactions.Log do
  use Ecto.Schema
  import Ecto.Changeset

  schema "logs" do
    belongs_to :transaction, Banking.Transactions.Transaction
    belongs_to :account, Banking.Accounts.Account
    field :amount, :integer

    timestamps()
  end

  @doc false
  def changeset(log, transaction, account, attrs) do
    log
    |> cast(attrs, [:amount])
    |> validate_required([:amount])
    |> put_assoc(:transaction, transaction)
    |> put_assoc(:account, account)
  end
end

lib/banking_web/controllers/log_controller.ex
defmodule BankingWeb.LogController do
  use BankingWeb, :controller

  alias Banking.Transactions

  def index(conn, %{"period" => period}) do
    period = String.to_atom(period)
    report_data = Transactions.report(period)

    render(conn, "index.html", period: period, report_data: report_data)
  end

  def index(conn, _params) do
    report_data = Transactions.report(:all)

    render(conn, "index.html", period: :all, report_data: report_data)
  end
end

lib/banking_web/views/log_view.ex
defmodule BankingWeb.LogView do
  use BankingWeb, :view

  @doc false
  def report_name(period) do
    case period do
      :all -> "Todos"
      :year -> "Anual"
      :month -> "Mensal"
      :day -> "Diário"
      _ -> "Desconhecido"
    end
  end

  @doc false
  def date_display(:all, nil), do: "∞"

  def date_display(period, date) do
    day =
      date.day
      |> to_string()
      |> String.pad_leading(2, "0")

    month =
      date.month
      |> to_string()
      |> String.pad_leading(2, "0")

    case period do
      :year -> "#{date.year}"
      :month -> "#{month}/#{date.year}"
      :day -> "#{day}/#{month}/#{date.year}"
    end
  end

  @doc false
  def money(nil), do: "R$ 0.00"

  def money(amount) do
    amount
    |> Money.new()
    |> to_string()
  end

  @doc false
  def money_class(amount) do
    cond do
      amount > 0 -> "credit"
      amount < 0 -> "debit"
      amount == 0 -> "neutral"
    end
  end
end

lib/banking_web/templates/log/index.html.eex
<section class="textCenter">
  <h1>Relatórios</h1>
</section>

<section class="reportsButtons">
  <ul>
    <li><a href="<%= Routes.log_path(@conn, :index) %>" class="button">Todos</a></li>
    <li><a href="<%= Routes.log_path(@conn, :index, period: "year") %>" class="button">Anual</a></li>
    <li><a href="<%= Routes.log_path(@conn, :index, period: "month") %>" class="button">Mensal</a></li>
    <li><a href="<%= Routes.log_path(@conn, :index, period: "day") %>" class="button">Diário</a></li>
  </ul>
</section>

<section>
  <h2 class="textCenter">
    <%= report_name(@period) %>
  </h2>

  <table class="reportTable">
    <thead>
      <tr>
        <th>Data</th>
        <th>Créditos</th>
        <th>Débitos</th>
        <th>Saldo</th>
      </tr>
    </thead>
    <tbody>
      <%= for line <- @report_data do %>
        <tr>
          <td><%= date_display(@period, line.date) %></td>
          <td class="<%= money_class(line.credit) %>"><%= money(line.credit) %></td>
          <td class="<%= money_class(line.debit) %>"><%= money(line.debit) %></td>
          <td class="<%= money_class(line.balance) %>"><%= money(line.balance) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>